
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/example?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: yao601860186018
mybatis:
  mapperLocations: classpath:/mapper/*.xml
